# Generated by Django 5.1.4 on 2025-01-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_repo_App', '0002_subjects_alter_student_student_id_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmarks',
            options={'ordering': ['student']},
        ),
    ]
