# Generated by Django 5.1.4 on 2025-01-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_repo_App', '0003_alter_subjectmarks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentid',
            options={'ordering': ['student_id']},
        ),
    ]
