# Generated by Django 5.1.4 on 2025-01-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_repo_App', '0004_alter_studentid_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.IntegerField()),
                ('date_of_report_card_generation', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='Student_repo_App.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_report_card_generation')},
            },
        ),
    ]
